### ISSUE TITLE
D11.2 Barcode Reader

### ISSUE THREAD

**Issue by DValue** [DelphiWorlds/Kastri#156]
BarcodeReader Demo ,Compile and run without problems, But no results are returned from scanning the barcode

Delphi Version: D11.2

Platform(s) :Android

**Comment by DelphiWorlds** [comment]
Can you attach a picture of the barcode here, please?

**Comment by DValue** [comment]
> Can you attach a picture of the barcode here, please?

The barcode is the BarcodeScanExample.png in the Screenshots directory of the demo, other barcodes are also the same scan code did not return

**Comment by DelphiWorlds** [comment]
What model device do you have and what version of Android is on it?

**Comment by DValue** [comment]
My device is Honor Magic 4 with Android version 12

**Comment by DValue** [comment]
Same for other Android devices, Android 10+

**Comment by DelphiWorlds** [comment]
..and this is using the demo project? I'm having no trouble here on Pixel 6 Pro (Android 13), Pixel 3a (Android 12), Nexus 5X (Android 8.1). Can you attach your .apk here?

**Comment by DValue** [comment]
Download link to the apk generated by compiling the demo with d11.2
[https://pan.baidu.com/s/1YjMHf98BYvyVf5XkZn32TA?pwd=1234](url)

**Comment by DelphiWorlds** [comment]
I'm unable to download the apk from that link. Please zip your .apk and attach it (by drag/drop) here.

**Comment by DValue** [comment]
Okay, here it is.
[BarcodeReaderD11.zip](https://github.com/DelphiWorlds/Kastri/files/10778773/BarcodeReaderD11.zip)

**Comment by DelphiWorlds** [comment]
The .apk works OK on my Nexus 5X (Android 8.1). 

It does not install on my Pixel 6 Pro (Android 13) because the manifest does not have the `android:exported` attribute for the activity, even though the targetSdkVersion is set to 32. This implies you are using Delphi 11.2, so you will need to delete the AndroidManifest.template.xml file and allow the IDE to recreate it by doing a Clean, then Build. I doubt this is the cause of your issue, though - the out of date template file would prevent the app from being installed onto devices with Android 12 or higher, so it would not even be able to run.

**Comment by DValue** [comment]
[BarcodeReaderD11.zip](https://github.com/DelphiWorlds/Kastri/files/10778885/BarcodeReaderD11.zip)
I added in AndroidManifest.template.xml
android:exported and recompiled it, but the demo does not recognize the barcode on my phone

**Comment by DelphiWorlds** [comment]
I think you may need to follow the instructions, here: https://qr.ae/prWNDG, then retry the BarcodeReader demo.

**Comment by DValue** [comment]
Thank you very much, I'll try again
