### ISSUE TITLE
[CrossPlatformLocation] How to shut down the application correctly so that the service does not restart after that?

### ISSUE THREAD

**Issue by AlexUsovDeveloper** [DelphiWorlds/Kastri#166]
How to shut down the application correctly so that the service does not restart after that? For example, when you click a special button on the main form of the application.

**Comment by DelphiWorlds** [comment]
The whole point of this demo is so that the service keeps running after the application is closed

**Comment by AlexUsovDeveloper** [comment]
Yes, I understand ) But when the user no longer needs it and he wants to completely close the application, then how to do it right?

**Comment by DelphiWorlds** [comment]
That the service continues to run does not affect the user - the application will (or at least should) not show in the recent items list after the user closes it. Can you explain what the actual issue is?

**Comment by AlexUsovDeveloper** [comment]
Eg. the user launched the application and it continues to determine the location, even if the OS closes the activity - and that's cool. But if the user no longer needs to determine the location and he wants to end the application and service, for example. pressing the "Exit" button, then how to do it?

**Comment by DelphiWorlds** [comment]
There is already example code for this in the demo, [here](https://github.com/DelphiWorlds/Kastri/blob/0edac38b614d6dcbf147a26e27852e6c70ba71c0/Demos/CrossPlatformLocation/Application/Views/CPL.View.Main.pas#L296). i.e.

```
  TServiceCommander.SendCommand(cServiceCommandStopLocationUpdates);l
```

This stops location updates in the service. Unfortunately, there is no reliable way on Android to know when the application is terminated, because "swipe to quit" just kills the process. You'd need to have a way for the user to explicitly turn off the location updates before shutting down the app. An alternative might be to comment out or remove [this line of code](https://github.com/DelphiWorlds/Kastri/blob/0edac38b614d6dcbf147a26e27852e6c70ba71c0/Demos/CrossPlatformLocation/Service/CPL.ServiceModule.pas#L165).

**Comment by AlexUsovDeveloper** [comment]
OK, thank you. I think I figured it out)

**Comment by AlexUsovDeveloper** [comment]
TServiceCommander.SendCommand(cServiceCommandStopLocationUpdates);

procedure TServiceModule.AndroidServiceDestroy(Sender: TObject);
begin
  DestroyObjects;
  if not FLocationSettings.IsPaused then
    RestartService;
end;
