### ISSUE TITLE
[Location] Compiling the Demo is looking for AndroidSDK26.1.1_64bit.sdk Whereas 34.0.0 is Installed

### ISSUE THREAD

**Issue by hraztan** [DelphiWorlds/Kastri#172]
Hi

Comiling/Building the CrossPlatormLocationD11 project is looking for Android SDK version 26.1.1 whereas I have version 34.0.0 istalled. It is producing the following exception:

Specified platform sdk not found: '......\AppData\Roaming\Embarcadero\BDS\22.0\AndroidSDK26.1.1_64bit.sdk'

There are four libraries added to the project:

- CrossPlatformLocationService.jar
- dw-fusedlocation.jar
- dw-kastri-base-2.0.0.jar
- play-services-location-16.0.0.jar (Do we need this since play-services-location-18.0.0.dex.jar is already added?)

Delphi Version: Delphi 11.3 Patch 1
Windows 11 Pro, 22H2
Platform: Android 64-bit

**Comment by DelphiWorlds** [comment]
> (Do we need this since play-services-location-18.0.0.dex.jar is already added?)

No, but that is not what it causing the error. I've pushed a change that should fix it. 

Note: SInce you're using Delphi 11.3, you'll need to be aware of this: https://docs.code-kungfu.com/books/hotfix-113-alexandria/page/fix-jar-libraries-added-to-android-64-bit-platform-target-are-not-compiled. The alternate (maybe even "official"?) workaround to this issue is to make copies of the jar files being added into another folder, then add them to the Android 64-bit Libraries node.

**Comment by hraztan** [comment]
Tx. FYI, you need to make the same changes in the "CrossPlatformLocationService.dproj" file as well.

**Comment by DelphiWorlds** [comment]
> FYI, you need to make the same changes in the "CrossPlatformLocationService.dproj" file as well.

Done, thanks!
