### ISSUE TITLE
[FCMBaseDemo] App doesn't open when compiled with Android64bits

### ISSUE THREAD

**Issue by edsonalanis** [DelphiWorlds/Kastri#174]
I'm trying to use the FCMBaseDemo Demo compiling with Android 64bit, and according to the documentation it is not necessary to add the files dw-kastri-base-2.0.0.jar and dw-fcm-2.0.0.jar in the Lib folder.
However, the application is stuck and does not open on Android.

**Comment by DelphiWorlds** [comment]
This is due to a bug in Delphi. There's two solutions - one [here](https://docs.code-kungfu.com/books/hotfix-113-alexandria/page/fix-jar-libraries-added-to-android-64-bit-platform-target-are-not-compiled), or you can:

1. Copy `dw-fcm-2.0.0.jar` and `dw-kastr-base-2.0.0.jar` from the `Lib` folder in Kastri, into **another** folder.
2. Add the **copies** to the Libraries node under the Android 64-bit target

**Comment by edsonalanis** [comment]
Thanks for the feedback, it worked
