### ISSUE TITLE
[FCM] click_action replacement for iOS

### ISSUE THREAD

**Issue by havrlisan** [DelphiWorlds/Kastri#211]
There is currently no way on iOS to implement a custom action if the user clicks on a Firebase notification since the _click_action_ key is unsupported on iOS. From what I've found, it is possible to bypass this by using the _category_ key for iOS instead. By default, the _category_ key is used to display a dialog to perform a quick action instead of opening the application. This way it'll be possible to implement a custom behavior inside Delphi (just as with _click_action_ for Android), or even create and register a _UNNotificationCategory_ (although it's probably not worth the hassle).

References:
[Apple docs - Configuring Categories and Actionable Notifications](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/SupportingNotificationsinYourApp.html#//apple_ref/doc/uid/TP40008194-CH4-SW26)
[Firebase docs - Notification payload support](https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support)
[SO - just a confirmation other people have done it](https://stackoverflow.com/questions/39090059/ios-and-google-firebase-how-to-do-notification-actions)

**Comment by DelphiWorlds** [comment]
Just FYI - I started work on something like this not long ago. The first link you provided has made me change direction a bit. I will be implementing *something* :-)

**Comment by havrlisan** [comment]
> Just FYI - I started work on something like this not long ago. The first link you provided has made me change direction a bit. I will be implementing _something_ :-)

Glad I could be of help!

**Comment by DelphiWorlds** [comment]
Added support for `category` (and `action`). The demo has been updated to illustrate how to add categories/actions, however to also illustrate here:

```
procedure TfrmMain.AddCategories;
var
  LCategory: INotificationCategory;
begin
  LCategory := FCM.AddCategory('category1', Category1Handler);
  LCategory := FCM.AddCategory('category2');
  LCategory.AddAction('action1', 'Confirm', Category2ConfirmHandler);
  LCategory.AddAction('action2', 'Deny', Category2DenyHandler);
end;
```

The first line of the routine is the simplest case - a category with no actions. When the user taps the notification, `Category1Handler` is called. 
The rest of the routine demonstrates adding actions to a category. The action "buttons" are presented when the user swipes down on the notification itself (i.e. instead of tapping it), and tapping one of the action buttons will invoke the relevant handler:

![image](https://github.com/DelphiWorlds/Kastri/assets/22670829/34dbd031-a529-462d-b72c-4f02a64db630)

**NOTE:** For this to function properly when the app is not running, or is in the background, **you need to ensure that `remote-notification` is selected** in the UIBackgroundModes property in Version Info in the Project Options:

<img width="559" alt="image" src="https://github.com/DelphiWorlds/Kastri/assets/22670829/5445dab6-70e8-406c-98ba-4f54265cceb2">

**Comment by gmurt** [comment]
Hi Dave,

Great work! Looking forward to trying this out.

Just one thing, the way I would need to use it is to build the actions dynamically from a call to the server. 

Having a handler method with no parameters makes it difficult to do this as we don't know which action was tapped. 

If it could pass the action ID to the handler method, we could build the actions at runtime, use the same handler for all actions and then send the pressed action id back to the server for any required processing.

Hope this makes sense, let me know if not 👍

**Comment by DelphiWorlds** [comment]
Yes, it made sense. Let me know if the changes I just pushed suit you, which allows adding of actions optionally without a handler, and use `OnNotificationCategory` to handle categories and/or actions generically

**Comment by gmurt** [comment]
Yes, this is exactly what I meant, makes it much more flexible! 

Thanks a lot save, will be trying this later today.

**Comment by jtrejodarkness** [comment]
Asking for, finally it is posible to pass action ID to the handler method?... how can I do this?

**Comment by DelphiWorlds** [comment]
> Asking for, finally it is possible to pass action ID to the handler method?... how can I do this?

Please read the previous comments on this issue, especially [this one](https://github.com/DelphiWorlds/Kastri/issues/211#issuecomment-2216711403).
