### ISSUE TITLE
[DCC Error] E2597 ld: warning: directory not found for option '-LComponent' 

### ISSUE THREAD

**Issue by ch022222** [DelphiWorlds/Kastri#224]
Estou com o seguinte erro ao compilar meu projeto utilizando kastri master com barcode no delphi 11.2:
[DCC Error] E2597 ld: warning: directory not found for option '-LComponent'
     ld: file not found: /System/Library/PrivateFrameworks/DocumentManager.framework/DocumentManager for architecture arm64

**Comment by DelphiWorlds** [comment]
Your question appears to be general, rather than related to Kastri. Regardless, it is likely that the iOS SDK was not imported correctly. [This link](https://github.com/DelphiWorlds/HowTo/tree/main/Solutions/FixBrokenSDKImport) gives information on how to correct this.

Sua pergunta parece ser geral, e não relacionada a Kastri. Independentemente disso, é provável que o iOS SDK não tenha sido importado corretamente. [Este link](https://github.com/DelphiWorlds/HowTo/tree/main/Solutions/FixBrokenSDKImport) fornece informações sobre como corrigir isso.
