### ISSUE TITLE
How do I merge the AndroidManifest.merge.xml with AndroidManifest.xml?

### ISSUE THREAD

**Issue by hraztan** [DelphiWorlds/Kastri#49]
How do I merge the AndroidManifest.merge.xml file in the Firebase Cloud Messaging demo with the AndroidManifest.xml?

**Comment by DelphiWorlds** [comment]
If you're using the demo, it should happen automatically, via the build event in the Project Options (see pic)
![Screen Shot 2021-06-17 at 5 26 16 am](https://user-images.githubusercontent.com/22670829/122284365-a8a79e00-cf2c-11eb-9d4d-33e12cc67a43.png)

**Comment by hraztan** [comment]
Do I need to do this with all my projects, or it's just for the demo?
The reason I'm asking is that there are Firebase Analytics events automatically created for iOS (e.g. app_update, first_open, os_update, screen_view, session_start), whereas there are no events created for Android. Actually, the Android version of the app is not even in the Firebase Analytics; it is just in the Firebase Cloud Messaging.
Also, how do I create new Forebase Analytics events?

**Comment by hraztan** [comment]
ALso, when I use the post-build event command, I'm getting the following error:

".....\Tools\manifestmerge AndroidManifest.merge.xml ..........\AndroidManifest.xml" exited with code 9009

**Comment by DelphiWorlds** [comment]
> Do I need to do this with all my projects, or it's just for the demo?
For all projects that use the Kastri Firebase Cloud Messaging solution. Alternatively, you could copy the resulting `AndroidManifest.xml` file and ensure that it is deployed when building your app. Be aware that if the manifest needs to be changed in the future, you will need to repeat the process.

> whereas there are no events created for Android.
This is because EMBT omitted files necessary for Firebase Analytics to work, namely:

https://github.com/DelphiWorlds/Kastri/blob/master/ThirdParty/Android/com-google-android-gms-play-services-measurement-api-16.4.0.jar
https://github.com/DelphiWorlds/Kastri/blob/master/ThirdParty/Android/com-google-android-gms-play-services-measurement-impl-16.4.0.jar

Adding these to the Libraries node of the Android platform in Project Manager for the projects that need Firebase Analytics should hopefully fix that issue. The second jar might not be required, however I've included it just in case.

> Also, how do I create new Firebase Analytics events?
I just happen to be working on a solution for this, which I hope to have ready by the end of the week

**Comment by hraztan** [comment]
Hi

I added the 2 files above. It didn't fix the issue. I still can't see any Android events.

Looking forward for your solution when it's available. Hopefully by the end of this week.

**Comment by hraztan** [comment]
> I just happen to be working on a solution for this, which I hope to have ready by the end of the week

Hi. Any update on this?

**Comment by DelphiWorlds** [comment]
As discussed privately, being able to include Firebase Analytics means having to switch out a number of jars, *and* modify FMX Java code and rebuild `fmx.jar`. This might be supported in the next release of Delphi.
